In [1]:
#import classic key libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [17]:
a = np.array([0,1,2,3,4])
a

array([0, 1, 2, 3, 4])

In [18]:
# print all elements in the numpy array a
print("a[0]: ", a[0])
print("a[1]: ", a[1])
print("a[2]: ", a[2])
print("a[3]: ", a[3])
print("a[4]: ", a[4])

a[0]:  0
a[1]:  1
a[2]:  2
a[3]:  3
a[4]:  4


In [28]:
#check the type of arra and value type for the array b
b = np.array([3.1,11.02,6.2,213.2,5.2])
b.dtype

dtype('float64')

In [29]:
#assign the value 20 for the second elements in the given array
a = np.array([10,2,30,40,50])
a[1] = 20
a

array([10, 20, 30, 40, 50])

In [30]:
#assign the value 20 for the second element in the given array
c = np.array([20, 1, 2, 3, 4])
d = c[1:4]
d

array([1, 2, 3])

In [41]:
#print the elements in the given array
arr = np.array([1,2,3,4,5,6,7,8])

#solution
print(arr[1::2])


[2 4 6 8]


In [48]:
#Find the size, dimension and shape for the given array b
b = np.array([10,20,30,40,50,60,70])

print('The size of array b is ', b.size)
print('The dimension of array b is ', b.ndim)
print('The shape of array b is ', b.shape)

The size of array b is  7
The dimension of array b is  1
The shape of array b is  (7,)


In [50]:
#Find the sum of maximum and minimum value in the given numpy array
c = np.array([-10.201,43,94,502])
sum = c.max() + c.min()

print('The sum of the maximum and minimum value is ', sum)

The sum of the maximum and minimum value is  491.799


In [58]:
#perform addition operations on the given numpy arrays arr1 and arr2
arr1 = np.array([10,11,12,13,14,15])
arr2 = np.array([20,21,22,23,24,25])

sum = np.add(arr1,arr2)
sum

array([30, 32, 34, 36, 38, 40])

In [59]:
#Mathematical functions
#np.pi
#np.sin(x)

3.141592653589793

In [63]:
np.linspace(-10,10, num=21)

array([-10.,  -9.,  -8.,  -7.,  -6.,  -5.,  -4.,  -3.,  -2.,  -1.,   0.,
         1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [65]:
#make a numpy array within [5,4] and 6 elements
arr = np.linspace(5,4, num=6)
arr

array([5. , 4.8, 4.6, 4.4, 4.2, 4. ])