In [1]:
#import classic key libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [17]:
a = np.array([0,1,2,3,4])
a

array([0, 1, 2, 3, 4])

In [18]:
# print all elements in the numpy array a
print("a[0]: ", a[0])
print("a[1]: ", a[1])
print("a[2]: ", a[2])
print("a[3]: ", a[3])
print("a[4]: ", a[4])

a[0]:  0
a[1]:  1
a[2]:  2
a[3]:  3
a[4]:  4


In [28]:
#check the type of arra and value type for the array b
b = np.array([3.1,11.02,6.2,213.2,5.2])
b.dtype

dtype('float64')

In [29]:
#assign the value 20 for the second elements in the given array
a = np.array([10,2,30,40,50])
a[1] = 20
a

array([10, 20, 30, 40, 50])

In [30]:
#assign the value 20 for the second element in the given array
c = np.array([20, 1, 2, 3, 4])
d = c[1:4]
d

array([1, 2, 3])

In [41]:
#print the elements in the given array
arr = np.array([1,2,3,4,5,6,7,8])

#solution
print(arr[1::2])


[2 4 6 8]


In [48]:
#Find the size, dimension and shape for the given array b
b = np.array([10,20,30,40,50,60,70])

print('The size of array b is ', b.size)
print('The dimension of array b is ', b.ndim)
print('The shape of array b is ', b.shape)

The size of array b is  7
The dimension of array b is  1
The shape of array b is  (7,)


In [50]:
#Find the sum of maximum and minimum value in the given numpy array
c = np.array([-10.201,43,94,502])
sum = c.max() + c.min()

print('The sum of the maximum and minimum value is ', sum)

The sum of the maximum and minimum value is  491.799


In [58]:
#perform addition operations on the given numpy arrays arr1 and arr2
arr1 = np.array([10,11,12,13,14,15])
arr2 = np.array([20,21,22,23,24,25])

sum = np.add(arr1,arr2)
sum

array([30, 32, 34, 36, 38, 40])

In [59]:
#Mathematical functions
#np.pi
#np.sin(x)

3.141592653589793

In [63]:
np.linspace(-10,10, num=21)

array([-10.,  -9.,  -8.,  -7.,  -6.,  -5.,  -4.,  -3.,  -2.,  -1.,   0.,
         1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [65]:
#make a numpy array within [5,4] and 6 elements
arr = np.linspace(5,4, num=6)
arr

array([5. , 4.8, 4.6, 4.4, 4.2, 4. ])

In [66]:
csv_path = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%204/data/TopSellingAlbums.csv'
df = pd.read_csv(csv_path)

In [70]:
df.head(5)

Artist                      Album  Released   Length  \
0  Michael Jackson                   Thriller      1982  0:42:19   
1            AC/DC              Back in Black      1980  0:42:11   
2       Pink Floyd  The Dark Side of the Moon      1973  0:42:49   
3  Whitney Houston              The Bodyguard      1992  0:57:44   
4        Meat Loaf            Bat Out of Hell      1977  0:46:33   

                         Genre  Music Recording Sales (millions)  \
0               pop, rock, R&B                              46.0   
1                    hard rock                              26.1   
2             progressive rock                              24.2   
3               R&B, soul, pop                              27.4   
4  hard rock, progressive rock                              20.6   

   Claimed Sales (millions) Released.1 Soundtrack  Rating  
0                        65  30-Nov-82        NaN    10.0  
1                        50  25-Jul-80        NaN     9.5  
2                        45  01-Mar-73        NaN     9.0  
3                        44  17-Nov-92          Y     8.5  
4                        43  21-Oct-77        NaN     8.0

In [68]:
#use the variable q to store the column Rating as a dataframe
q = df[['Rating']]
q

Rating
0    10.0
1     9.5
2     9.0
3     8.5
4     8.0
5     7.5
6     7.0
7     6.5

In [69]:
#assign the variable q to the dataframe that is made up of the column Released and Artist
q = df[['Released', 'Artist']]
q

Released           Artist
0      1982  Michael Jackson
1      1980            AC/DC
2      1973       Pink Floyd
3      1992  Whitney Houston
4      1977        Meat Loaf
5      1976           Eagles
6      1977         Bee Gees
7      1977    Fleetwood Mac

In [73]:
#access the 2nd row and 3rd columns of df
df.iloc[1,2]

1980

In [80]:
df.head(10)

Artist                            Album  Released   Length  \
a  Michael Jackson                         Thriller      1982  0:42:19   
b            AC/DC                    Back in Black      1980  0:42:11   
c       Pink Floyd        The Dark Side of the Moon      1973  0:42:49   
d  Whitney Houston                    The Bodyguard      1992  0:57:44   
e        Meat Loaf                  Bat Out of Hell      1977  0:46:33   
f           Eagles  Their Greatest Hits (1971-1975)      1976  0:43:08   
g         Bee Gees             Saturday Night Fever      1977  1:15:54   
h    Fleetwood Mac                          Rumours      1977  0:40:01   

                         Genre  Music Recording Sales (millions)  \
a               pop, rock, R&B                              46.0   
b                    hard rock                              26.1   
c             progressive rock                              24.2   
d               R&B, soul, pop                              27.4   
e  hard rock, progressive rock                              20.6   
f   rock, soft rock, folk rock                              32.2   
g                        disco                              20.6   
h                    soft rock                              27.9   

   Claimed Sales (millions) Released.1 Soundtrack  Rating  
a                        65  30-Nov-82        NaN    10.0  
b                        50  25-Jul-80        NaN     9.5  
c                        45  01-Mar-73        NaN     9.0  
d                        44  17-Nov-92          Y     8.5  
e                        43  21-Oct-77        NaN     8.0  
f                        42  17-Feb-76        NaN     7.5  
g                        40  15-Nov-77          Y     7.0  
h                        40  04-Feb-77        NaN     6.5

In [79]:
df.index = new_index
df = df_new
df_new.loc['a', 'Artist']

'Michael Jackson'

In [82]:
df_new.loc['a':'d','Artist']

a    Michael Jackson
b              AC/DC
c         Pink Floyd
d    Whitney Houston
Name: Artist, dtype: object

In [89]:
Annie = 1996

if (1996 % 4 == 0):
    print('Annie was born in a leap year')
else:
    print('Annie was not born in a leap year')

Annie was born in a leap year


In [88]:
Jane = 1999

if (1999 % 4 == 0):
    print('Jane was born in a leap year')
else:
    print('Jane was not born in a leap year')

Jane was not born in a leap year


In [91]:
Annie =1996
Jane = 1999

if (Annie%4==0):
    print('Annie was born in a leap year')
elif (Jane%4==0):
    print('Jane was born in a leap year')
else:
    print('None of them was not born in a leap year')

Annie was born in a leap year
